service: eg-crm-service

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

custom:
  eventgateway:
    space: <your space>
    apiKey: <your API key>

plugins:
  - "@serverless/serverless-event-gateway-plugin"

functions:
  addUserToCRM:
    handler: index.handler
    events:
      - eventgateway:
          event: user.created
