builds:
  - main: ./cmd/event-gateway/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    hooks:
      pre: dep ensure
      post: ./upload.sh
archive:
  format: binary
