// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/serverless/event-gateway/endpoints (interfaces: FunctionExister)

package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of FunctionExister interface
type MockFunctionExister struct {
	ctrl     *gomock.Controller
	recorder *_MockFunctionExisterRecorder
}

// Recorder for MockFunctionExister (not exported)
type _MockFunctionExisterRecorder struct {
	mock *MockFunctionExister
}

func NewMockFunctionExister(ctrl *gomock.Controller) *MockFunctionExister {
	mock := &MockFunctionExister{ctrl: ctrl}
	mock.recorder = &_MockFunctionExisterRecorder{mock}
	return mock
}

func (_m *MockFunctionExister) EXPECT() *_MockFunctionExisterRecorder {
	return _m.recorder
}

func (_m *MockFunctionExister) Exists(_param0 string) (bool, error) {
	ret := _m.ctrl.Call(_m, "Exists", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFunctionExisterRecorder) Exists(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Exists", arg0)
}
